### ISSUE TITLE
Wrong credentials end up in 500 error

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-express-impex#49]
There are no headers and no further information.

I would expect a feedback about permission denied or so.

![screen shot 2015-03-26 at 17 18 01](https://cloud.githubusercontent.com/assets/602105/6850908/2e35d10c-d3dc-11e4-9b55-030f3175f86d.png)

**Comment by emmenko** [comment]
If you have wrong credentials you usually get a different error

![screen shot 2015-03-26 at 18 39 12](https://cloud.githubusercontent.com/assets/1110551/6852838/7c792bec-d3e7-11e4-9366-0c8e90390cd4.png)

Can you be more specific how to reproduce the error?

**Comment by hajoeichler** [comment]
Close until I find out how to reproduce it.
