### ISSUE TITLE
descending sort order not possible to select 

### ISSUE THREAD

**Issue by stmeissner** [sphereio/sphere-express-impex#52]
I've tried for the project projection endpoint search page.
It is not possible to select the 'desc' option in the sort order form, it always stays at 'asc'

    <select name="search-sort-order" class="form-control">
    <option value="asc" selected="selected">Asc</option>
    <option value="desc">Desc</option>
    </select>

**Comment by emmenko** [comment]
I'll have a look

**Comment by emmenko** [comment]
@stmeissner Fix is live
