### ISSUE TITLE
Product export: "The query string I provide is already encoded" option broken

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-express-impex#56]
The "The query string I provide is already encoded" in the product export does not do anything (it does not encode the query string if not checked, neither when checked). 

Maybe that applies to the other impex parts, too.

**Comment by emmenko** [comment]
Are you sure?

https://github.com/sphereio/sphere-express-impex/blob/master/public/javascripts/commands.coffee#L297
https://github.com/sphereio/sphere-express-impex/blob/master/src/coffee/commands.coffee#L61
https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/src/coffee/export.coffee#L47

**Comment by nkuehn** [comment]
well, I just tried live with the productId example.  But you are right in that the problem is rather inside the execution of the query (i.e. this issue is in the wrong repo, should go into sphere-product-csv-sync ).
